---
- name: Installing tomcat container, stop & delete same container
  hosts: all
  tasks:
   - name: Create tomcat container
     docker_container:
      name: appserver
      image: tomee
   - name: Stoping tomcat container
     docker_container:
      name: appserver
      state: stopped
   - name: removing the container
     docker_container:
      name: appserver
      state: absent
...
