---
- name: Create user using Hostscope variables
  hosts: 172.31.43.202
  tasks:
   - name: Creation of user
     user:
      name: "{{a}}"
      password: "{{b}}"
      uid: "{{c}}"
      home: "{{d}}"
      shell: "{{e}}"
      comment: "{{f}}"
...
