---
- name: Install & Un-install Software applications
  hosts: all
  tasks:
   - name: Install & Un-install S/W
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: tree, b: absent, c: no}
      - {a: git, b: absent, c: no} 
      - {a: maven, b: absent, c: no}
... 
