---
- name: Implementing handlers
  hosts: all
  tasks:
   - name: Install apache2/nginx
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
     notify: Check URL response
   - name: Edit the index.html file
     copy:
      content: "Welcome to Intelliqit"
      dest: /var/www/html/index.html
     notify: Restart the Apache2 service
  handlers:
   - name: Restart the Apache2 service
     service:
      name: "{{a}}"
      state: restarted
   - name: Check URL response
     uri:
      url: "{{item}}"
      status_code: 200
     with_items:
      - http://172.31.20.290
      - http://172.31.20.61
...
